services:
  server:
    image: gitea/gitea:1.22.2-rootless
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: $GITEA_DB_NAME
      GITEA__database__USER: $GITEA_DB_USER
      GITEA__database__PASSWD: $GITEA_DB_PASS
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: gitea.autumnsky.jp
      LETSENCRYPT_HOST: gitea.autumnsky.jp
      LETSENCRYPT_: gitea.autumnsky.jp
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - gitea

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=$GITEA_DB_USER
      - POSTGRES_PASSWORD=$GITEA_DB_PASS
      - POSTGRES_DB=$GITEA_DB_NAME
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      default:

networks:
  reverse-proxy-network:
    external: true
