services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: ${WP_DB_NAME}
      MARIADB_USER: ${WP_DB_USER}
      MARIADB_PASSWORD: ${WP_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      default:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      VIRTUAL_HOST: blog.autumnsky.jp
      LETSENCRYPT_HOST: blog.autumnsky.jp
    volumes:
      - ./html:/var/www/html
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - wordpress

networks:
  reverse-proxy-network:
    external: true
