services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WP_DB_USER
      MYSQL_PASSWORD: $WP_DB_PASS
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./db:/var/lib/mysql
    networks:
      default:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: $WP_DB_NAME
      WORDPRESS_DB_USER: $WP_DB_USER
      WORDPRESS_DB_PASSWORD: $WP_DB_PASS
      VIRTUAL_HOST: blog.autumnsky.jp
      LETSENCRYPT_HOST: blog.autumnsky.jp
    volumes:
      - ./html:/var/www/html
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - wordpress

networks:
  reverse-proxy-network:
    external: true
