services:
  db:
    image: postgres:14-alpine
    container_name: akkoma-db
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "akkoma" ]
    env_file: db.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      default:

  web:
    image: akkoma
    container_name: akkoma
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider --proxy=off localhost:4001 || exit 1" ]
    restart: always
    ports:
      # Remove this if you're not exposing this to your local network
      - '4000:4000'
    build:
      context: build
      # Feel free to remove or override this section. The variables set below are
      # the current defaults. See 'Build-time variables' in README.md
      args:
        - "UID=1000"
        - "GID=1000"
        - "AKKOMA_VER=v3.13.2"
    volumes:
      - ./uploads:/uploads
      - ./static:/static
      - ./config:/config
    env_file:
      - db.env
    environment:
      DOMAIN: autumnsky.jp
      INSTANCE_NAME: Akkoma
      ADMIN_EMAIL: autumnsky64@gmail.com
      NOTIFY_EMAIL: autumnsky64@gmail.com
      VIRTUAL_HOST: autumnsky.jp
      LETSENCRYPT_HOST: autumnsky.jp
    depends_on:
      - db

    networks:
      default:
      reverse-proxy-network:
        aliases:
          - akkoma

networks:
  reverse-proxy-network:
    external: true
