services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - reverse-proxy-network
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy-network
    environment:
      - DEFAULT_EMAIL=autumnsky64@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  conf:
  certs:
  vhost:
  html:
  acme:

networks:
  reverse-proxy-network:
    external: true
